Repository ie3-institute/MobilitySimulator, pull requests merged in 2022-10, with the labels that each got.

#75 allow absolute paths
  .gitignore
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala
  src/main/scala/edu/ie3/mobsim/config/MobSimConfig.scala
  src/main/scala/edu/ie3/mobsim/utils/PathsAndSources.scala
  src/test/scala/edu/ie3/mobsim/utils/PathsAndSourcesSpec.scala
Labels: enhancement

#84 To/#83 write destination poi type
  src/main/scala/edu/ie3/mobsim/model/ElectricVehicle.scala
  src/main/scala/edu/ie3/mobsim/model/TripSimulation.scala
  src/main/scala/edu/ie3/mobsim/utils/IoUtils.scala
  src/test/scala/edu/ie3/mobsim/utils/IoUtilsSpec.scala
Labels: enhancement

#79 adjust gitignore and minor refactorings
  .gitignore
  src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala
  src/main/scala/edu/ie3/mobsim/io/probabilities/TripProbabilities.scala
  src/main/scala/edu/ie3/mobsim/model/TripSimulation.scala
  src/test/scala/edu/ie3/mobsim/io/probabilities/TripProbabilitiesSpec.scala
  src/test/scala/edu/ie3/mobsim/model/TripSimulationSpec.scala
Labels: enhancement

#116 update dependabot
  .github/dependabot.yml
Labels: dependencies

#86 Explicitly track destination poi type
  CHANGELOG.md
  src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala
  src/main/scala/edu/ie3/mobsim/io/geodata/PoiEnums.scala
  src/main/scala/edu/ie3/mobsim/io/geodata/PointOfInterest.scala
  src/main/scala/edu/ie3/mobsim/model/ChargingBehavior.scala
  src/main/scala/edu/ie3/mobsim/model/ElectricVehicle.scala
  src/main/scala/edu/ie3/mobsim/model/TripSimulation.scala
  src/main/scala/edu/ie3/mobsim/utils/IoUtils.scala
  src/test/scala/edu/ie3/mobsim/MobilitySimulatorSpec.scala
  src/test/scala/edu/ie3/mobsim/MobilitySimulatorTestData.scala
  src/test/scala/edu/ie3/mobsim/io/geodata/PoiEnumsSpec.scala
  src/test/scala/edu/ie3/mobsim/model/ChargingBehaviorSpec.scala
  src/test/scala/edu/ie3/mobsim/model/ChargingBehaviorTestData.scala
  src/test/scala/edu/ie3/mobsim/model/ElectricVehicleSpec.scala
  src/test/scala/edu/ie3/mobsim/model/TripSimulationSpec.scala
  src/test/scala/edu/ie3/mobsim/utils/IoUtilsSpec.scala
Labels: bug
