Repository ie3-institute/MobilitySimulator, pull requests merged in 2025-03, with the labels that each got.

#347 Write all POIs on initialisation by poiWriter
  CHANGELOG.md
  src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala
  src/main/scala/edu/ie3/mobsim/utils/IoUtils.scala
  src/test/scala/edu/ie3/mobsim/io/geodata/PoiTestData.scala
  src/test/scala/edu/ie3/mobsim/model/TripSimulationTestData.scala
  src/test/scala/edu/ie3/mobsim/utils/IoUtilsSpec.scala
Labels: bug

#342 Remove entry uuid from MobilitySim outputs
  CHANGELOG.md
  src/main/scala/edu/ie3/mobsim/utils/IoUtils.scala
  src/test/scala/edu/ie3/mobsim/utils/IoUtilsSpec.scala
Labels: enhancement

#339 Added ConfigFailFastSpec
  CHANGELOG.md
  src/test/scala/edu/ie3/mobsim/config/ConfigFailFastSpec.scala
Labels: enhancement, test
